name: xeubiart

services:
  # --- DATABASE ---
  db:
    image: postgres:15-alpine
    container_name: xeubiart-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - xeubiart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- REDIS ---
  cache:
    image: redis:7-alpine
    container_name: xeubiart-cache
    restart: always
    networks:
      - xeubiart-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # --- SPRING BACKEND ---
  backend:
    image: ghcr.io/xeubiart/backend:latest
    container_name: backend
    environment:
      - ENV_MODE=prod
      - SPRING_PROFILES_ACTIVE=prod
      - ENABLE_EMAILS=true
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SPRING_DATA_REDIS_HOST=cache
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    networks:
      - xeubiart-network

  # --- MCP SERVER ---
  # mcp:
  #   image: ghcr.io/xeubiart/mcp:latest
  #   container_name: mcp
  #   restart: always
  #   environment:
  #     - BACKEND_URL=http://backend:8080
  #     - PORT=5001
  #   depends_on:
  #     - backend
  #   networks: 
  #     - xeubiart-network

  # --- GO WEBSITE ---
  website:
    image: ghcr.io/xeubiart/website:latest
    container_name: website
    environment:
      - ENV_MODE=prod
      - BACKEND_URL=http://backend:8080
      - BACKEND_GRPC_URL=backend:50051 
    depends_on:
      - backend
    networks:
      - xeubiart-network

  # --- CADDY ---
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config 
    depends_on:
      - website
      - backend
      # - mcp
    networks: 
      - xeubiart-network

networks:
  xeubiart-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: